### ISSUE TITLE
Dealing with API Rate Limiting

### ISSUE THREAD

**Issue by BenEddy** [BitBalloon/bitballoon-ruby#10]
The BitBalloon API enforces rate limiting of 200 requests/minute (for understandable reasons). 

Unless I'm blind, the API does not appear to have an endpoint for "PUT all your files". Instead you must PUT them individually. Consequently, when a site has more than 200 pages, the API is pretty much unusable. 

__The easy fix__
The API returns `X-RateLimit-Remaining` and `X-RateLimit-Reset`, so it is probably possible to pause the deploy until the reset timestamp. 

__The harder fixes__
- Create an endpoint for accepting a large payload of all files
- Rethink the rate limiting strategy. How about one deploy per minute? 
- Increase the rate limit to be consistent with API throughput capacity. 200 req/min is 3.33 req/sec, apparently a very attainable throughput target.

**Comment by biilmann** [comment]
Hi Ben,

Great points. I've upped the allowed #/request per minute significantly. It's mostly just about finding the right balance and we plan to automatically boost the rate limits for users with premium sites, but let me know if you still run into it for your use.

**Comment by BenEddy** [comment]
Awesome, thanks @biilmann!
