### ISSUE TITLE
SSL error when using client

### ISSUE THREAD

**Issue by dmix** [BitBalloon/bitballoon-ruby#11]
I'm getting this error on Linux: https://gist.github.com/dmix/a3d4a0b63f42a691c41a

The solution here is to default to SSLv3 instead of using TLSv1 (or TLSv1_2)

https://stackoverflow.com/questions/23223691/ssl-connect-syscall-returned-5-errno-0-state-sslv2-v3-read-server-hello-a-fara

This is good overall for security.

**Comment by HangingClowns** [comment]
How to set this though? @dmix

**Comment by dmix** [comment]
see https://github.com/BitBalloon/bitballoon-ruby/pull/12

**Comment by HangingClowns** [comment]
I just saw that, would this also solve for if you're using the access_token instead of oauth?

**Comment by dmix** [comment]
Works now thanks.

@HangingClowns not sure
